Feature: "Strong" Core Update for Dotly
CodelyTV/dotly pull request #119
Opened 2021-03-28 11:53 UTC by gtrabanco

# Features

* Now the dotly core loader is outside of `.bashrc` and `.zshrc` files so now the framework core functionality could be modified.
* Added optional initializer scripts after the DOTLY framework is loaded, to load, for example the autoupdater. You need to enable it manually by executing `dot self init enable`. To disable init scripts just type: `dot self init disable` you can see the status of `autoupdate_loader` with `dot self init status autoupdate_loader` or `dot self init status`. See more usage with `dot self init -h`
* Added some functions that are used in other PRs.

# Motivation

This is done because there are some recurrent functions that were used in my other PRs. So merge with master later could be a mess, with this I try to simplify the process of merging the other PRs because there are a lot stuff.

2021-03-29 22:14 UTC, gtrabanco commented
* Added another task in main message
* Added `#Important` title in main message.

2021-03-31 22:42 UTC, gtrabanco commented
* Added str::to_upper
* Added platform functions to get current script full path or directory (useful to include libs)

2021-04-01 15:36 UTC, gtrabanco commented
Tested and ready to merge, anyway one fast test in other computer may help.
* Async library were added to make some improvements to branch `feature/marketplace_extended`
* Autoupdate run synchronously, I will re-make it async when I have finished `feature/marketplace_extended` and `feature/ssh_config`.

2021-04-01 15:56 UTC, gtrabanco commented
* `dot symlinks apply update` subcommand that was added was splitted. This was done becasue the use case is different for this subcommand than `dot symlinks apply`. It will also make easier apply later PR #79 that "solves" #76.

@rgomezcasas @JavierCane this PR is ready to merge.

2021-04-01 22:17 UTC, gtrabanco commented
* Added async in `_main.sh` core loading

Would be nice having a reference in README to the creator repository of the async library in bash:
* https://github.com/zombieleet/async-bash

2021-04-02 02:11 UTC, gtrabanco commented
* Fixed error 93, I could not tested on bash without applying this patch that is also in PR #95 and reported in #93
* Fixed Autoload on init scripts
* Now autoupdate is async (was easier begin with async here).

# Known errors
* The async function of async library, print 1 on screen every time a async function is called.
* The async functions previous to be called in scripts need to do `set +eu` or it will fail.
* Problem? With prompt. See Help needed.

# How to use autoupdate

To enable autoupdate (not by default), type:
```bash
dot self init enable dotly_autoupdater
```

There are three modes of dotly autoupdater which is defined in the value of ENV var `DOTLY_AUTO_UPDATE_MODE`:
* `DOTLY_AUTO_UPDATE_MODE=auto`: It will autoupdate dotly
* `DOTLY_AUTO_UPDATE_MODE=info`: default mode.
> * It will show an advise in your terminal and create a file with the path: `$DOTFILES_PATH/.dotly_update_available`
> * This file is used to show you a box in the PROMPT.
* `DOTLY_AUTO_UPDATE_MODE=prompt`: no advise showed, just create the file to see the box in the prompt.

You can also define the number of days that your `DOTLY_PATH` should be older to begin check for updates:

```bash
DOTLY_AUTO_UPDATE_DAYS=15
```

If you do not define anyone these are the default values:

```bash
DOTLY_AUTO_UPDATE_DAYS=7
DOTLY_AUTO_UPDATE_MODE=info
```

As I said, this won't work unless you enable it first:
```bash
dot self init enable dotly_autoupdater
```

To disable:
```bash
dot self init disable dotly_autoupdater
```

# Help needed

* I need help with the prompt to make the box disappear if I delete the file without reseting the terminal.
* Also help needed to make the box appear. Do not know why the prompt is not updating after press the key "intro". Should not the prompt update itself?

2021-04-02 21:08 UTC, gtrabanco commented
Sorry for the last two commits but I merged `feature/ssh_config` into this. Now should be solved.

2021-04-02 21:13 UTC, gtrabanco commented
Ready knowing the known issues and help needed with prompt.

2021-04-08 21:34 UTC, rgomezcasas requested changes

2021-04-08 23:55 UTC, gtrabanco commented on dotfiles_template/shell/exports.sh
> +export DOTLY_AUTO_UPDATE_MODE="reminder" # reminder*, auto, prompt
Done.

Now have all these modes:
- `silent` which update automatically and silently.
- `reminder` which just print a reminder.
- `minor` which update only minor or patch version (need some more work). It is production ready but needs a file "$DOTLY_PATH/VERSION" with current semver version of installed dotly.
- `info` prints a message in terminal and inbox in prompt
- `prompt` just see a inbox in your prompt when there is any update.

2021-04-08 23:57 UTC, gtrabanco commented on scripts/core/output.sh
> +}
Solved

2021-04-08 23:57 UTC, gtrabanco commented on scripts/dotfiles/create
> +##?    test
🙏

2021-04-08 23:58 UTC, gtrabanco commented on scripts/self/utils/init.sh
> +# Check if init script exists in dotly or dotfiles
removed

2021-04-08 23:58 UTC, gtrabanco commented on scripts/symlinks/apply
> +SCRIPT_VERSION="1.0.0"
If I move this to docbloc the script will parse itself to print the current version of the script. Do you want that?

2021-04-08 23:58 UTC, gtrabanco commented on shell/bash/themes/codely.sh
> +  fi
Done.

2021-04-08 23:59 UTC, gtrabanco commented on shell/zsh/themes/prompt_codely_setup
> +  fi
Done

2021-04-08 23:59 UTC, gtrabanco commented
# Autoupdater

Now have all these modes:
- `silent` which update automatically and silently.
- `reminder` which just print a reminder.
- `minor` which update only minor or patch version (need some more work). It is production ready but needs a file "$DOTLY_PATH/VERSION" with current semver version of installed dotly.
- `info` prints a message in terminal and inbox in prompt
- `prompt` just see a inbox in your prompt when there is any update.

2021-04-09 00:04 UTC, gtrabanco commented on scripts/core/async.sh
> +
* Deleted all not needed lines and not needed functions.
* Solved a bug about print always 1 in screen when executing async.

2021-04-09 00:09 UTC, gtrabanco commented on dotfiles_template/shell/paths.sh
> +)
Done

2021-04-09 00:09 UTC, gtrabanco commented on dotfiles_template/shell/exports.sh
> +export DOTLY_AUTO_UPDATE_DAYS=7
Done

2021-04-09 00:29 UTC, gtrabanco commented
Please check function `files::check_if_path_is_older` for me works great as it was. See in the files the review I did @rgomezcasas

2021-04-09 00:38 UTC, gtrabanco commented
# Important
Please check Bash if it works for you and load correctly the prompt. For me dot not show the right prompt but works pretty well all the other stuff.

2021-04-17 12:49 UTC, closed without merging